services:
  dummyjson-api:
    image: ghcr.io/hos3ein3/dummyjson-api:${IMAGE_TAG:-latest}
    container_name: dummyjson-api
    restart: unless-stopped
    env_file:
      - .env
    environment:
      ASPNETCORE_ENVIRONMENT: Production
      ASPNETCORE_URLS: http://+:8080
    ports:
      - "8080:8080"
    networks:
      - homelab-docker-network

networks:
  homelab-docker-network:
    external: true
    name: homelab-docker-network