name: DummyJson API Deploy

on:
  push:
    branches: [main]

env:
  DEPLOY_PATH: /home/homelabadmin/wwwroot/dummyjson/api
  DOTNET_INSTALL_DIR: /home/homelabadmin/.dotnet

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET 9
        uses: actions/setup-dotnet@v4
        env:
          DOTNET_INSTALL_DIR: /home/homelabadmin/.dotnet
        with:
          dotnet-version: 9.0.x

      - name: Add dotnet to PATH
        run: echo "$DOTNET_INSTALL_DIR" >> $GITHUB_PATH

      - name: Check dotnet
        run: dotnet --info

      - name: Debug permissions
        run: |
          whoami
          pwd
          ls -ld /home/homelabadmin
          ls -ld /home/homelabadmin/wwwroot
          ls -ld /home/homelabadmin/wwwroot/dummyjson
          ls -ld /home/homelabadmin/wwwroot/dummyjson/api

      - name: Restore API
        run: |
          dotnet restore ./src/DummyJson.API/DummyJson.API.csproj

      - name: Build API
        run: |
          dotnet build ./src/DummyJson.API/DummyJson.API.csproj -c Release --no-restore

      - name: Publish directly into api root
        run: |
          "$DOTNET_INSTALL_DIR/dotnet" publish ./src/DummyJson.API/DummyJson.API.csproj \
            -c Release \
            -o "$DEPLOY_PATH" \
            --no-build

      - name: Copy docker-compose
        run: |
          cp docker-compose.yml "$DEPLOY_PATH/docker-compose.yml"

      - name: Copy .env
        run: |
          cp .env "$DEPLOY_PATH/.env"

      - name: Run docker compose
        run: |
          cd "$DEPLOY_PATH"
          docker compose up -d

      - name: Show deployed files
        run: |
          ls -la "$DEPLOY_PATH"